# Edit the host address as needed for your local development environment
@InventoryHub.Api_HostAddress = https://localhost:7276


### GetProducts - returns a list of all products (Id, Name, Price, Stock)
GET {{InventoryHub.Api_HostAddress}}/products
Accept: application/json

###
